# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.1
_src_path: gh:jmineau/python-template
affiliation: University of Utah
copyright_year: '2026'
distribution_name: uataq
email: jameskmineau@gmail.com
full_name: James Mineau
github_username: jmineau
orcid: 0000-0002-2289-2252
package_name: uataq
project_name: uataq
project_short_description: Read UATAQ data
publish_to_pypi: false
python_min: '3.11'
repository_name: uataq
test_os:
- ubuntu-latest
- macos-latest
- windows-latest
